devmode = false

[postgresql]
  enabled = false
  url = "postgresql://user@ip:port/db_name"
  password = "secure_password"

[ai]
  # Comes from huggingface
  model = "bdotloh/just-another-emotion-classifier"
  # This model runs about 200ms for 1kb of text on Ryzen 5 3600 (3.6GHz)
  device = "cpu"

[log]
  file = ""

[srv]
  host = "0.0.0.0"
  port = 8080
  # IPs exempt from ratelimiting.
  ratelimit_exempt = [
    "192.168.0.0/16",
  ]
  trusted_proxies = [
    "127.0.0.1"
  ]
  api_version = "1.0.0"

[pages]
  frontend_version = "1.0.0"